### ISSUE TITLE
Installation on old macOSes

### ISSUE THREAD

**Issue by BLKSerene** [NoUnique/pymecab-ko#5]
Hi, I'm using `pymecab-ko` for my cross-platform corpus tool project. It works perfectly on Windows and pass tests on Linux CI, but failed on macOS CI. It failed during installation on macOS 10.15 (CI log [here](https://ci.appveyor.com/project/BLKSerene/wordless/builds/46489625/job/e3wv48v6wddkbkrm#L283)), and succeeded to install but failed to pass tests (on import, CI log [here](https://dev.azure.com/blkserene/BLKSerene%20-%20Github/_build/results?buildId=1241&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=2dac33d1-b0ca-5feb-3c36-18b56319df50&l=77) and [here](https://dev.azure.com/blkserene/BLKSerene%20-%20Github/_build/results?buildId=1241&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=2dac33d1-b0ca-5feb-3c36-18b56319df50&l=77)). I also tried installing `pymecab-ko` on OS X 10.11 but failed (I need to package the program on old macOSes for old OS compatibility).

I'm not sure whether this is a problem of `pymecab-ko` or that of original `Mecab` project. Could you please give some suggestions or am I miss something?

FYI: I found another python binding for Mecab ([`python-mecab-ko`](https://github.com/jonghwanhyeon/python-mecab-ko)), and no error on installation or import for OS X 10.11.

**Comment by NoUnique** [comment]
It seems that the issue stems from insufficient OS and architecture support in the CI scripts originating from the base code.
Since I have a day job, I intend to attempt transitioning to a GitHub Actions workflow utilizing cibuildwheel over the weekend.

**Comment by NoUnique** [comment]
It seems that the issue stems from insufficient OS and architecture support in the CI scripts originating from the base code.
Since I have a day job, I intend to attempt transitioning to a GitHub Actions workflow utilizing cibuildwheel over the weekend.
