### ISSUE TITLE
Fine-tuning the package with North Korean words

### ISSUE THREAD

**Issue by taegyunlim** [NoUnique/pymecab-ko#6]
Hi, I would like to use fine-tune the package with North Korean words but I am not sure how I can do that.
Since some North Korean words are unique, fine-turning the package with my data is necessary.
It would be great if I could do that. I really appreciate your help!

**Comment by NoUnique** [comment]
It seems like your question is about making dictionary, and it might be better to ask that part in the repository below.

https://github.com/LuminosoInsight/mecab-ko-dic
